@version = v1
@heroku = https://app-cityinthepocket.herokuapp.com



##############################################
#########   Test Route Market Place 
##############################################

### Renvoi un market place par son id
GET {{heroku}}{{version}}/marketplace/1

### Retourne tous les marketplaces
GET {{heroku}}{{version}}/marketplaces

### Renvoi tous les shops d’un marketplace
GET {{heroku}}{{version}}/marketplace/1/shops
###
DELETE {{heroku}}{{version}}/marketplace/1



##############################################
######### Test Route User
##############################################

### Renvoi tous les users 
GET {{heroku}}{{version}}/users


### Renvoi un utilisateur par son id 
GET {{heroku}}{{version}}/user/1

### Créer un user
POST {{heroku}}{{version}}/user/ 
Content-Type: application/json

{
  "firstName": "Peter",
  "lastName": "Quill",
  "email": "test.cityinthepocket@gmail.com",
  "password": "Min8@Max10",
  "confirmPassword": "Min8@Max10",
  "phone_number":"0123456789",
  "address":"5 rue la Boétie",
  "city":"Paris",
  "postal_code":"75008",
  "policy_agree":true
}


### Test Login User
POST {{heroku}}{{version}}/login 
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123!"
}

### Supprime un utilisateur par son id 
DELETE {{heroku}}{{version}}/user/2



##############################################
######### Test Route Product
##############################################

### Renvoi un product par son id 
GET {{heroku}}{{version}}/product/1

###  Renvoi les 5 derniers products
GET {{heroku}}{{version}}/marketplace/1/product/last

### Ajoute un produit
POST {{heroku}}{{version}}/product/ 
Content-Type: application/json

{
  "name": "test",
  "description": "super truc bleu",
  "price": 240,
  "shop_id": 8
}

### Supprime un produit
DELETE {{heroku}}{{version}}/product/3



##############################################
######### Test Route Shop
##############################################

### Renvoi les shops par categorie (2 = categoryId)
GET {{heroku}}{{version}}/marketplace/1/category/2/shops

###Renvoi un shop par son id 
GET {{heroku}}{{version}}/shop/30/


### Renvoi un shop par le userId
GET {{heroku}}{{version}}/shop/user/3

###Renvoi les produits d’un shop
GET {{heroku}}{{version}}/shop/8/products

### Supprime un shop
DELETE {{heroku}}{{version}}/shop/2

### Créer un shop 
POST  {{heroku}}{{version}}/shop/
Content-Type: application/json

{
  "company_name": "Toulouse Shop",
  "siret":"89070935500014", 
  "description":"Supeeeeeeeeer boutique jdcbyezbcyebcyezbcuzec",
  "address":"Rue des Champs Elysees",
  "city":"Toulouse",
  "postal_code":"31500",  
  "phone_number":"0467899568",
  "email":"boutique@aol.com",
  "user_id":3,
  "marketplace_id":1,
  "category_id":2
}


### Renvoi les 5 derniers shops
GET {{heroku}}{{version}}/marketplace/1/shop/last



##############################################
######### Test Route Category
##############################################

###Renvoi toutes les category
GET {{heroku}}{{version}}/marketplace/1/category

###Renvoi une categorie par son id
GET {{heroku}}{{version}}/marketplace/1/category/1

###
DELETE {{heroku}}{{version}}/category/5
